/**
 * Collects the per-ABI release APKs Gradle produces, gives them names the
 * download page can read, and writes checksums alongside them.
 *
 *   npm run release:apks              -- rename + checksum what's already built
 *   npm run release:apks -- --build   -- run assembleRelease first
 *   npm run release:apks -- --upload  -- also attach them to the GitHub release
 *
 * Gradle names its outputs after the module (`app-arm64-v8a-release.apk`),
 * which says nothing about the app or its version once the file is sitting in
 * someone's Downloads folder. The site matches assets by the `-<abi>.apk`
 * suffix produced here, so the two have to agree -- see ABI_ORDER in
 * site/main.js.
 */
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(__dirname, '..');
const GRADLE_OUTPUT = join(ROOT, 'android', 'app', 'build', 'outputs', 'apk', 'release');
const DEST = join(ROOT, 'release');
const SITE = join(ROOT, 'site');
const REPO = 'CodrJatin/routro-react-native';

/** Also the order the download page lists them in. `universal` last: it is the
 * fallback, not a choice anyone should make first. */
const ABIS = ['arm64-v8a', 'armeabi-v7a', 'x86_64', 'universal'] as const;

function readVersion(): string {
  const appJson = JSON.parse(readFileSync(join(ROOT, 'app.json'), 'utf8'));
  const version = appJson?.expo?.version;
  if (typeof version !== 'string' || !version) {
    throw new Error('No expo.version in app.json.');
  }
  return version;
}

function gradlew(): string {
  return process.platform === 'win32' ? 'gradlew.bat' : './gradlew';
}

function build(): void {
  console.log('> assembleRelease (this takes a while)');
  execFileSync(gradlew(), ['assembleRelease'], {
    cwd: join(ROOT, 'android'),
    stdio: 'inherit',
    shell: process.platform === 'win32',
  });
}

function sha256(path: string): string {
  return createHash('sha256').update(readFileSync(path)).digest('hex');
}

function mb(bytes: number): string {
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

/**
 * Writes `site/release.json` — what the download page reads instead of asking
 * api.github.com.
 *
 * The APKs themselves stay on GitHub Releases, which is the only place they can
 * live: GitHub blocks any file over 100 MiB outright (the universal build is
 * ~145 MiB), and a Vercel Hobby deployment caps at 100 MB of static files
 * against ~320 MB of APKs. Committing them would also grow the repo by that
 * much *per release*, permanently, since replacing a file does not remove the
 * old blob from history.
 *
 * What is committed is this manifest, about a kilobyte of it. That removes the
 * only thing the binaries' location was costing us: the unauthenticated GitHub
 * API allows 60 requests an hour **per IP**, and behind carrier-grade NAT --
 * which is most mobile traffic in India -- a single address can be shared by a
 * great many people. Same-origin JSON has no such ceiling, no CORS preflight,
 * and keeps working when GitHub's API does not.
 *
 * The tradeoff, stated plainly: the site now has to be redeployed for a new
 * version to show up on it. Nothing breaks if that is forgotten -- the page
 * simply keeps offering the previous release -- but it is a step in the release
 * flow that did not exist before.
 */
function writeManifest(
  version: string,
  collected: { name: string; size: number; hash: string }[]
): void {
  const tag = `v${version}`;
  const base = `https://github.com/${REPO}/releases/download/${tag}`;

  const manifest = {
    // A note for anyone opening this file directly rather than through git log.
    _: 'Generated by scripts/release-apks.ts. Do not edit by hand.',
    tag,
    version,
    published: new Date().toISOString().slice(0, 10),
    checksums: `${base}/SHA256SUMS.txt`,
    builds: collected.map((asset) => ({
      abi: asset.name.replace(/^routro-v[\d.]+-/, '').replace(/\.apk$/, ''),
      name: asset.name,
      size: asset.size,
      sha256: asset.hash,
      url: `${base}/${asset.name}`,
    })),
  };

  writeFileSync(join(SITE, 'release.json'), JSON.stringify(manifest, null, 2) + '\n');
}

function main(): void {
  const args = process.argv.slice(2);
  if (args.includes('--build')) build();

  if (!existsSync(GRADLE_OUTPUT)) {
    throw new Error(
      `No release APKs at ${GRADLE_OUTPUT}. Run with --build, or build in Android Studio first.`
    );
  }

  const version = readVersion();
  mkdirSync(DEST, { recursive: true });

  const built = readdirSync(GRADLE_OUTPUT).filter((f) => f.endsWith('.apk'));
  const collected: { name: string; path: string; size: number; hash: string }[] = [];

  for (const abi of ABIS) {
    // `app-arm64-v8a-release.apk`. Matched on the ABI rather than the whole
    // name so a module rename upstream doesn't silently drop a variant --
    // a missing one is reported below instead.
    const source = built.find((f) => f.includes(`-${abi}-`));
    if (!source) {
      console.warn(`! no ${abi} APK found -- skipping`);
      continue;
    }

    const name = `routro-v${version}-${abi}.apk`;
    const dest = join(DEST, name);
    copyFileSync(join(GRADLE_OUTPUT, source), dest);
    collected.push({ name, path: dest, size: statSync(dest).size, hash: sha256(dest) });
  }

  if (collected.length === 0) {
    throw new Error(`Found ${built.length} APK(s) in the output folder but none matched a known ABI.`);
  }

  // One file, the format `sha256sum -c` reads, so a download can be verified
  // with a tool people already have rather than by eye.
  const sums = collected.map((a) => `${a.hash}  ${a.name}`).join('\n') + '\n';
  writeFileSync(join(DEST, 'SHA256SUMS.txt'), sums);

  writeManifest(version, collected);

  console.log(`\nrelease/ (v${version})`);
  for (const asset of collected) {
    console.log(`  ${asset.name.padEnd(38)} ${mb(asset.size).padStart(9)}`);
  }
  console.log(`  SHA256SUMS.txt`);
  console.log(`\nsite/release.json rewritten`);

  if (args.includes('--upload')) {
    const tag = `v${version}`;
    console.log(`\n> gh release upload ${tag}`);
    execFileSync(
      'gh',
      ['release', 'upload', tag, ...collected.map((a) => a.path), join(DEST, 'SHA256SUMS.txt'), '--clobber'],
      { cwd: ROOT, stdio: 'inherit', shell: process.platform === 'win32' }
    );
    // The manifest is only true once the assets it points at exist.
    console.log('\nNow commit site/release.json and push, so the site offers this build.');
  } else {
    console.log(`\nUpload with:  npm run release:apks -- --upload`);
  }
}

main();
